#ifndef BOOTLOADER_CONFIG_H
#define BOOTLOADER_CONFIG_H

#include <stdint.h>

/*
 * Default STM32F103RCTx memory layout used by the current car boards.
 * Override these from a board-specific build target for smaller parts such as
 * the Nucleo-F103RB.
 */
#ifndef BOOTLOADER_FLASH_START_ADDRESS
#define BOOTLOADER_FLASH_START_ADDRESS 0x08000000U
#endif

#ifndef BOOTLOADER_SIZE_BYTES
#define BOOTLOADER_SIZE_BYTES          (32U * 1024U)
#endif

#ifndef BOOTLOADER_APP_START_ADDRESS
#define BOOTLOADER_APP_START_ADDRESS \
    (BOOTLOADER_FLASH_START_ADDRESS + BOOTLOADER_SIZE_BYTES)
#endif

#ifndef BOOTLOADER_FLASH_SIZE_BYTES
#define BOOTLOADER_FLASH_SIZE_BYTES    (256U * 1024U)
#endif

#ifndef BOOTLOADER_FLASH_END_ADDRESS
#define BOOTLOADER_FLASH_END_ADDRESS \
    (BOOTLOADER_FLASH_START_ADDRESS + BOOTLOADER_FLASH_SIZE_BYTES)
#endif

#ifndef BOOTLOADER_FLASH_PAGE_SIZE_BYTES
#define BOOTLOADER_FLASH_PAGE_SIZE_BYTES (2U * 1024U)
#endif

#ifndef BOOTLOADER_APP_MAX_SIZE_BYTES
#define BOOTLOADER_APP_MAX_SIZE_BYTES \
    (BOOTLOADER_FLASH_END_ADDRESS - BOOTLOADER_APP_START_ADDRESS)
#endif

#ifndef BOOTLOADER_SRAM_START_ADDRESS
#define BOOTLOADER_SRAM_START_ADDRESS  0x20000000U
#endif

#ifndef BOOTLOADER_SRAM_SIZE_BYTES
#define BOOTLOADER_SRAM_SIZE_BYTES     (48U * 1024U)
#endif

#ifndef BOOTLOADER_SRAM_END_ADDRESS
#define BOOTLOADER_SRAM_END_ADDRESS \
    (BOOTLOADER_SRAM_START_ADDRESS + BOOTLOADER_SRAM_SIZE_BYTES)
#endif

#endif /* BOOTLOADER_CONFIG_H */
